# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:       1
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_view_slug_test:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        format:      html  # permet de preciser la valeur par defaut du parametre format si il n'est pas precisé car il devient facultatif
    requirements:  # condition sur les parametres: year doit contenir 4 chiffres - parametre format doit prendre l'une des valeur html oi xml
        year:   \d{4}
        format: html|xml